<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(OS)'=='Windows_NT'">
    <TargetFrameworks>net10.0;net9.0;net48</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)'!='Windows_NT'">
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="testsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Toolbox\CreateAndFake.csproj" />
    <ProjectReference Include="..\..\src\xUnit.v3\CreateAndFake.xUnit.v3.csproj" />
    <Using Include="Werecodent.CreateAndFake" />
    <Using Include="Werecodent.CreateAndFake.Fluent" />
    <Using Include="Werecodent.CreateAndFake.xUnit.v3" />
  </ItemGroup>

</Project>

