<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(OS)'=='Windows_NT'">
    <TargetFrameworks>net10.0;net9.0;net48</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)'!='Windows_NT'">
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.0" PrivateAssets="All" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Toolbox\CreateAndFake.csproj" />
    <ProjectReference Include="..\..\src\MSTest.v4\CreateAndFake.MSTest.v4.csproj" />
    <Using Include="Werecodent.CreateAndFake" />
    <Using Include="Werecodent.CreateAndFake.Fluent" />
    <Using Include="Werecodent.CreateAndFake.MSTest.v4" />
  </ItemGroup>

</Project>
