using System.Reflection;
using Werecodent.CreateAndFake.Design;
using Werecodent.CreateAndFake.Design.Content;
using Werecodent.CreateAndFake.Design.Exceptions;
using Werecodent.CreateAndFake.Design.Types;
using Werecodent.CreateAndFake.DuplicatorTool.Engine;

namespace Werecodent.CreateAndFake.DuplicatorTool.Hints;

#pragma warning disable CA2012 // Intended and not a bug.

/// <summary>Handles cloning <see cref="ValueTask"/> instances for <see cref="IDuplicator"/> .</summary>
public sealed class ValueTaskCopyHint : CopyHint
{
    private const string _ErrorMessage =
        $"{nameof(ValueTask)} instances can't be duplicated unless generated by the {nameof(CreateAndFake)} framework,"
        + " as resolving a ValueTask multiple times results in undefined behavior.";

    private static readonly MethodInfo _GenericTaskCloner = typeof(ValueTaskCopyHint).GetMethod(
        nameof(CloneTaskAsync),
        BindingFlags.NonPublic | BindingFlags.Static
    )!;

    private static readonly MethodInfo _GenericSourceCloner = typeof(ValueTaskCopyHint).GetMethod(
        nameof(CloneSource),
        BindingFlags.NonPublic | BindingFlags.Static
    )!;

    /// <inheritdoc/>
    public override int EnginePriority => (int)CopyPriority.ValueTaskHint;

    /// <inheritdoc/>
    public override IEnumerable<Type> SupportedTypes =>
        [typeof(ValueTask), typeof(ValueTask<>), typeof(SingleCallValueTaskSource<>)];

    /// <inheritdoc/>
    public sealed override CopyHintResult TryCopy(object source, IDuplicatorChainer duplicator)
    {
        ArgumentGuard.ThrowIfNull(source, duplicator);

        Type type = source.GetType();
        Type? genericType = GenericConverter.AsGenericBase(type);

        if (source is ValueTask task)
        {
            return new(ClonePlainTaskAsync(task));
        }
        else if (genericType == typeof(ValueTask<>))
        {
            return new(
                _GenericTaskCloner
                    .MakeGenericMethod(type.GetGenericArguments())
                    .Invoke(null, [source, duplicator])
            );
        }
        else if (genericType == typeof(SingleCallValueTaskSource<>))
        {
            return new(
                _GenericSourceCloner
                    .MakeGenericMethod(type.GetGenericArguments())
                    .Invoke(null, [source, duplicator])
            );
        }
        else
        {
            return CopyHintResult.None;
        }
    }

    private static ValueTask ClonePlainTaskAsync(ValueTask task)
    {
        SingleCallValueTaskSource? source = SingleCallValueTaskSource.ExtractFrom(task);
        if (source != null)
        {
            return new ValueTask(
                source.DeepClone(),
                SingleCallValueTaskSource.ExtractTokenFrom(task)
            );
        }
        else
        {
            throw new UnsupportedException(_ErrorMessage);
        }
    }

    private static ValueTask<T> CloneTaskAsync<T>(ValueTask<T> task, IDuplicatorChainer duplicator)
    {
        SingleCallValueTaskSource<T>? source = SingleCallValueTaskSource<T>.ExtractFrom(task);
        if (source != null)
        {
            return new ValueTask<T>(
                CloneSource(source, duplicator),
                SingleCallValueTaskSource<T>.ExtractTokenFrom(task)
            );
        }
        else
        {
            throw new UnsupportedException(_ErrorMessage);
        }
    }

    private static SingleCallValueTaskSource<T> CloneSource<T>(
        SingleCallValueTaskSource<T> source,
        IDuplicatorChainer duplicator
    )
    {
        return new SingleCallValueTaskSource<T>(duplicator.Copy(source.RawResult));
    }
}

#pragma warning restore
