blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: ../../../discussions
    about: Get help using discussions
  - name: Contact us via email
    url: mailto:createandfaketeam@gmail.com
    about: Communicate privately if necessary