<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Description>A C# class library that handles mocking, test data generation, and validation.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Toolbox/CreateAndFake.csproj" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="[3.0.0,)" />
  </ItemGroup>

</Project>
