<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <DefineConstants>LEGACY</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <Description>A C# class library that handles mocking, test data generation, and validation.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Design/CreateAndFake.Design.csproj" />
    <Using Include="Werecodent.CreateAndFake.Design.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="[2.0.0,)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="[2.0.0,)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="[2.0.0,)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="Microsoft.CSharp" Version="[4.3.0,)" />
    <PackageReference Include="System.Reflection.Emit" Version="[4.3.0,)" />
    <PackageReference Include="System.ValueTuple" Version="[4.3.0,)" />
  </ItemGroup>

</Project>
