<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <NoWarn>$(NoWarn);NU1510;NU1903</NoWarn>
    <RootNamespace>Werecodent.$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(MSBuildThisFileDirectory)..\artifacts\bin\$(MSBuildProjectName)\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\artifacts\bin\$(MSBuildProjectName)</BaseOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\artifacts\bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>CreateAndFake Contributors</Authors>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://werecodent.github.io/CreateAndFake/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Werecodent/CreateAndFake</RepositoryUrl>
    <ReleaseNotes>https://github.com/Werecodent/CreateAndFake/releases/</ReleaseNotes>
    <RepositoryType>Github</RepositoryType>
    <PackageTags>create, fake, tdd, agile, testing, tests, stubs, mocking, mocks, mock, data, random, cloning, clones, clone</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="AsyncFixer" Version="2.1.0" PrivateAssets="All" />
    <PackageReference Include="Lindhart.Analyser.MissingAwaitWarning" Version="3.2.0" PrivateAssets="All" />
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.122" PrivateAssets="All" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.6.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" version="18.7.23" PrivateAssets="All" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="All" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.28.0.143324" PrivateAssets="All" />
  </ItemGroup>
</Project>
