name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          7.0.x
    - name: Build & Test
      run: ./build/run.sh test

  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          7.0.x
    - name: Build & Test
      run: bash build/run.sh test

  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          7.0.x
    - name: Build & Test & Coverage
      run: ./build/run.cmd test coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        directory: ./artifacts/coverage
        token: ${{ secrets.CODECOV_TOKEN }}
